development:
  adapter: mysql
  database: hansard_development
  username: root
  password:
test:
  adapter: mysql
  database: hansard_test
  username: root
  password:
production:
  adapter: mysql
  database: hansard_production
  username: root
  password: 